"""会場別スクレイパー。各モジュールは fetch() -> list[Event] を公開する。"""
from . import (
    marine_messe,
    f_sunpalace,
    paypay_dome,
    avispa,
    hakataza,
    fukuoka_civic_hall,
    momochi,
    fukuoka_budokan,
    tokyo_dome,
    saitama_super_arena,
    yokohama_arena,
    k_arena,
    kyocera_dome,
    nagoya_dome,
    ig_arena,
    ariake_arena,
    nissan_stadium,
    ajinomoto_stadium,
    belluna_dome,
    tokyo_intl_forum,
    osaka_jo_hall,
    festival_hall,
    npb_baseball,
)

# build.py はこのリストを順に実行する。失敗しても他に影響しないよう個別try。
ALL_SCRAPERS = [
    marine_messe,
    f_sunpalace,
    paypay_dome,
    avispa,
    hakataza,
    fukuoka_civic_hall,
    momochi,
    fukuoka_budokan,
    tokyo_dome,
    saitama_super_arena,
    yokohama_arena,
    k_arena,
    kyocera_dome,
    nagoya_dome,
    ig_arena,
    ariake_arena,
    nissan_stadium,
    ajinomoto_stadium,
    belluna_dome,
    tokyo_intl_forum,
    osaka_jo_hall,
    festival_hall,
    npb_baseball,
]
